<?php
$title = 'Add new album';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php 
$this->inlineScript()->captureStart();
echo <<<JS
    $(document).ready(function(){
    	$(document.getElementsByName("published")).on( 'change', function(){
    		var getAge = birthDate => Math.floor((new Date() - new Date(birthDate).getTime()) / 31556925994);
    $('#year').val(getAge(document.getElementsByName("published")[0].value));
    console.log(document.getElementsByName("published")[0].value);
    	});
    
    });
JS;
$this->inlineScript()->captureEnd();
?>
<?php
// This provides a default CSS class and placeholder text for the title element:
$album = $form->get('title');
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Album title');

// This provides a default CSS class and placeholder text for the artist element:
$artist = $form->get('artist');
$artist->setAttribute('class', 'form-control');
$artist->setAttribute('placeholder', 'Artist');


$published = $form->get('published');
$published->setAttribute('class', 'form-control');
// $published->setAttribute('onchange', 'year();');
$published->setAttribute('placeholder', 'Published');


// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('album', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($album) ?>
    <?= $this->formElement($album) ?>
    <?= $this->formElementErrors()->render($album, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($artist) ?>
    <?= $this->formElement($artist) ?>
    <?= $this->formElementErrors()->render($artist, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($published) ?>
    <?= $this->formElement($published) ?>
    <?= $this->formElementErrors()->render($published, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <label for="artist">Year</label>   
    <input type="number" class="form-control" id="year">    
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>