<?php
// module/Album/view/album/album/index.phtml:

$title = 'My Albums';
$this->headTitle($title);
?>
<?php  echo $this->headScript()->appendFile($this->basePath() . '/js/custom.js'); ?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('album', ['action' => 'add']) ?>">Add new album</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>Published</th>
    <th>Years</th>
    <th>Action</th>
</tr>
<?php foreach ($albums as $key => $album) : ?>
    <tr id="album<?php echo $album->id;?>">
        <td><?= $this->escapeHtml($album->title) ?></td>
        <td><?= $this->escapeHtml($album->artist) ?></td>
        <td><?= $this->escapeHtml($album->published) ?></td>
        <td id="samp<?php echo $album->published; ?>"><?php 
$this->inlineScript()->captureStart();
echo <<<JS
    $(document).ready(function(){
    var getAge = birthDate => Math.floor((new Date() - new Date(birthDate).getTime()) / 31556925994);
    $('#samp$album->published').html(getAge('$album->published'));
    });
JS;
$this->inlineScript()->captureEnd();
?></td>
        <td>
            <a href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>">Edit</a>
            <!-- <a href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>">Delete</a> -->
            <a data-toggle="modal" href="#myModal<?php echo $album->id;?>">Delete</a>
            <!-- <a href="#" id="remove-<?php echo $album->id;?>" class="del">Delete</a> -->
        </td>
    </tr>
    <!-- Modal -->
  <div class="modal fade" id="myModal<?php echo $album->id;?>" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Delete Album</h4>
        </div>
        <div class="modal-body">
            <p>
                Are you sure that you want to delete
                "<?= $this->escapeHtml($album->title) ?>" by
                "<?= $this->escapeHtml($album->artist) ?>"?
            </p>

            <div class="form-group">
                <!-- <input type="hidden" id="del" name="id" value="<?=$album->id ?>" /> -->
                
                <button type="button" id="remove-<?php echo $album->id;?>" class="del btn btn-danger" data-dismiss="modal">Yes</button>
                <button type="button" class="btn btn-success" data-dismiss="modal">No</button>
                
            </div>
        </div>
      </div>
      
    </div>
  </div>
<?php endforeach; ?>
</table>
